name: Testflight Deploy

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-26

    steps:
      - uses: actions/checkout@v7

      - name: Set current build identifier
        run: echo "BUILD_IDENTIFIER=$(date +'%y.%m%d.')$GITHUB_RUN_NUMBER" >> "$GITHUB_ENV"

      - name: Import Codesign Certificate
        uses: Apple-Actions/import-codesign-certs@v7
        with:
          p12-file-base64: ${{ secrets.DIST_CERT_BASE64 }}
          p12-password: ${{ secrets.DIST_CERT_P12_PASSWORD }}

      - name: Download Provisioning Profile
        uses: Apple-Actions/download-provisioning-profiles@v6
        with:
          bundle-id: ch.fetz-gr.F1A-TV
          profile-type: TVOS_APP_STORE
          issuer-id: ${{ secrets.APPCONNECT_API_ISSUER }}
          api-key-id: ${{ secrets.APPCONNECT_API_KEY_ID }}
          api-private-key: ${{ secrets.APPCONNECT_API_KEY_PRIVATE }}

      - name: Bump Build Version
        run: agvtool new-version -all "$BUILD_IDENTIFIER"

      - name: Generate Export Plist
        env:
          TEAM_ID: ${{ secrets.TEAM_ID }}
        run: |
          /usr/libexec/PlistBuddy -c Clear _XcodeTaskExportOptions.plist
          /usr/libexec/PlistBuddy -c "Add teamID string $TEAM_ID" _XcodeTaskExportOptions.plist
          /usr/libexec/PlistBuddy -c "Add method string app-store-connect" _XcodeTaskExportOptions.plist

      - name: Archive and export
        env:
          ARCHIVE_PATH: ${{ github.workspace }}/archive/F1A-TV.xcarchive
          EXPORT_PATH: ${{ github.workspace }}/export/F1A-TV
        run: |
          xcodebuild -version
          xcodebuild -project F1A-TV.xcodeproj -scheme F1A-TV -configuration Release -destination 'generic/platform=tvOS' -archivePath "$ARCHIVE_PATH" CURRENT_PROJECT_VERSION="$BUILD_IDENTIFIER" archive
          xcodebuild -exportArchive -archivePath "$ARCHIVE_PATH" -exportPath "$EXPORT_PATH" -exportOptionsPlist _XcodeTaskExportOptions.plist
          test -s "$EXPORT_PATH/F1A-TV.ipa"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v7
        with:
          name: F1A-TV
          path: ${{ github.workspace }}/export/F1A-TV/F1A-TV.ipa
          if-no-files-found: error

      - name: Upload to TestFlight
        uses: Apple-Actions/upload-testflight-build@v5
        with:
          app-path: ${{ github.workspace }}/export/F1A-TV/F1A-TV.ipa
          issuer-id: ${{ secrets.APPCONNECT_API_ISSUER }}
          api-key-id: ${{ secrets.APPCONNECT_API_KEY_ID }}
          api-private-key: ${{ secrets.APPCONNECT_API_KEY_PRIVATE }}
          wait-for-processing: 'false'
